# Generated by Django 4.2 on 2023-05-05 08:39

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import personnel.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Departement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nom")),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'ajout"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière mise à jour"
                    ),
                ),
                ("active", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Département",
                "verbose_name_plural": "Départements",
            },
        ),
        migrations.CreateModel(
            name="Employe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nom")),
                ("poste", models.CharField(max_length=100, verbose_name="Poste")),
                ("ncni", models.CharField(max_length=100, verbose_name="N° de CNI")),
                (
                    "date_naissance",
                    models.DateTimeField(verbose_name="Date de naissance"),
                ),
                (
                    "signature",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Signature"
                    ),
                ),
                (
                    "qrcode",
                    models.CharField(blank=True, max_length=500, verbose_name="Code"),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'ajout"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière mise à jour"
                    ),
                ),
                ("active", models.BooleanField(default=False)),
                (
                    "departement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="personnel.departement",
                        verbose_name="Département",
                    ),
                ),
            ],
            options={
                "verbose_name": "Employé",
                "verbose_name_plural": "Employés",
            },
        ),
        migrations.CreateModel(
            name="EmployePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        upload_to=personnel.models.img_path,
                        verbose_name="Photo de l'employe",
                    ),
                ),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="personnel.employe",
                    ),
                ),
            ],
            options={
                "verbose_name": "photo de l'employé",
                "verbose_name_plural": "photos de l'employé",
            },
        ),
    ]
