# Generated by Django 4.2 on 2023-05-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personnel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employe",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="employe",
            name="qrcode",
            field=models.CharField(blank=True, max_length=500, verbose_name="Qr Code"),
        ),
    ]
